//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace OutlookKolab.Kolab.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class contact {
        
        private string uidField;
        
        private string bodyField;
        
        private string categoriesField;
        
        private System.DateTime creationdateField;
        
        private System.DateTime lastmodificationdateField;
        
        private string sensitivityField;
        
        private string inlineattachmentField;
        
        private string linkattachmentField;
        
        private string productidField;
        
        private contactName nameField;
        
        private string freebusyurlField;
        
        private string organizationField;
        
        private string webpageField;
        
        private string imaddressField;
        
        private string departmentField;
        
        private string officelocationField;
        
        private string professionField;
        
        private string jobtitleField;
        
        private string managernameField;
        
        private string assistantField;
        
        private string nicknameField;
        
        private string spousenameField;
        
        private System.DateTime birthdayField;
        
        private bool birthdayFieldSpecified;
        
        private string anniversaryField;
        
        private string pictureField;
        
        private string childrenField;
        
        private string genderField;
        
        private string languageField;
        
        private contactPhone[] phoneField;
        
        private contactEmail[] emailField;
        
        private contactAddress[] addressField;
        
        private string preferredaddressField;
        
        private decimal latitudeField;
        
        private decimal longitudeField;
        
        private decimal versionField;
        
        /// <remarks/>
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public string categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("creation-date")]
        public System.DateTime creationdate {
            get {
                return this.creationdateField;
            }
            set {
                this.creationdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("last-modification-date")]
        public System.DateTime lastmodificationdate {
            get {
                return this.lastmodificationdateField;
            }
            set {
                this.lastmodificationdateField = value;
            }
        }
        
        /// <remarks/>
        public string sensitivity {
            get {
                return this.sensitivityField;
            }
            set {
                this.sensitivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inline-attachment")]
        public string inlineattachment {
            get {
                return this.inlineattachmentField;
            }
            set {
                this.inlineattachmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link-attachment")]
        public string linkattachment {
            get {
                return this.linkattachmentField;
            }
            set {
                this.linkattachmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("product-id")]
        public string productid {
            get {
                return this.productidField;
            }
            set {
                this.productidField = value;
            }
        }
        
        /// <remarks/>
        public contactName name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("free-busy-url")]
        public string freebusyurl {
            get {
                return this.freebusyurlField;
            }
            set {
                this.freebusyurlField = value;
            }
        }
        
        /// <remarks/>
        public string organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("web-page")]
        public string webpage {
            get {
                return this.webpageField;
            }
            set {
                this.webpageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("im-address")]
        public string imaddress {
            get {
                return this.imaddressField;
            }
            set {
                this.imaddressField = value;
            }
        }
        
        /// <remarks/>
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("office-location")]
        public string officelocation {
            get {
                return this.officelocationField;
            }
            set {
                this.officelocationField = value;
            }
        }
        
        /// <remarks/>
        public string profession {
            get {
                return this.professionField;
            }
            set {
                this.professionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("job-title")]
        public string jobtitle {
            get {
                return this.jobtitleField;
            }
            set {
                this.jobtitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("manager-name")]
        public string managername {
            get {
                return this.managernameField;
            }
            set {
                this.managernameField = value;
            }
        }
        
        /// <remarks/>
        public string assistant {
            get {
                return this.assistantField;
            }
            set {
                this.assistantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nick-name")]
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                this.nicknameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("spouse-name")]
        public string spousename {
            get {
                return this.spousenameField;
            }
            set {
                this.spousenameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthdaySpecified {
            get {
                return this.birthdayFieldSpecified;
            }
            set {
                this.birthdayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string anniversary {
            get {
                return this.anniversaryField;
            }
            set {
                this.anniversaryField = value;
            }
        }
        
        /// <remarks/>
        public string picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
            }
        }
        
        /// <remarks/>
        public string children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
        
        /// <remarks/>
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone")]
        public contactPhone[] phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("email")]
        public contactEmail[] email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address")]
        public contactAddress[] address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("preferred-address")]
        public string preferredaddress {
            get {
                return this.preferredaddressField;
            }
            set {
                this.preferredaddressField = value;
            }
        }
        
        /// <remarks/>
        public decimal latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public decimal longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class contactName {
        
        private string givennameField;
        
        private string middlenamesField;
        
        private string lastnameField;
        
        private string fullnameField;
        
        private string initialsField;
        
        private string prefixField;
        
        private string suffixField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("given-name")]
        public string givenname {
            get {
                return this.givennameField;
            }
            set {
                this.givennameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("middle-names")]
        public string middlenames {
            get {
                return this.middlenamesField;
            }
            set {
                this.middlenamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("last-name")]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("full-name")]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
        
        /// <remarks/>
        public string initials {
            get {
                return this.initialsField;
            }
            set {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        public string prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        public string suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class contactPhone {
        
        private string typeField;
        
        private string numberField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class contactEmail {
        
        private string displaynameField;
        
        private string smtpaddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("display-name")]
        public string displayname {
            get {
                return this.displaynameField;
            }
            set {
                this.displaynameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("smtp-address")]
        public string smtpaddress {
            get {
                return this.smtpaddressField;
            }
            set {
                this.smtpaddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class contactAddress {
        
        private string typeField;
        
        private string streetField;
        
        private string localityField;
        
        private string regionField;
        
        private string postalcodeField;
        
        private string countryField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("postal-code")]
        public string postalcode {
            get {
                return this.postalcodeField;
            }
            set {
                this.postalcodeField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
}
